### ISSUE TITLE
`a` is not defined get_oracle_rank.py line 80

### ISSUE THREAD

**Issue by joe3141** [DeepSceneSeg/Network-Compression#1]
Hi, thanks for releasing this repository and the other open source code and checkpoints for your segmentation networks.

I just wanted to point out that there's an error in the "get_oracle_rank" module in line 80, where the variable `a` hasn't been defined.

I have set it to `activation[0]` as it makes the most sense to me.

**Comment by mohan1914** [comment]
The typo was fixed.
